### ISSUE TITLE
Functionalities -> Features

### ISSUE THREAD

**Issue by mxcop** [jiri132/Chess-App#1]
Perhaps instead of stating the Functionalities vs other apps (very vague)
You could create a check list of the features currently available and what you'd expect from an other app. 😄 

- [x] Item 1
- [x] Item 2

**Comment by jiri132** [comment]
hi mxcop, 
I took it into consideration and didn't know what to have staying there instead of functionality, but I changed 'other apps' to chess.com since that is the most used chess application in the world.

It is a checking table with some fun emotes ;) to make it even more CLEAR instead of checker boxes :)

I'll close the issue in 7 days so if you have something to add for me regarding these 2 items, place a comment

**Comment by mxcop** [comment]
I'm pretty sure that chess.com has aun pesant tho xD

**Comment by jiri132** [comment]
I have never seen it and I have never got the chance to do that move with my pawns :") 
so I don't know but I will look into it :D

**Comment by jiri132** [comment]
I updated everything and now the issue has been resolved! I will now close the issue
